#!/bin/bash
# Queue Drain Test
# Simulates offline period to test reading queue functionality

echo "═══════════════════════════════════════"
echo "  Reading Queue Drain Test"
echo "═══════════════════════════════════════"
echo ""

ESP_IP="${ESP_IP:-192.168.99.70}"

echo "This test verifies the ESP8266 queues readings when database is unreachable,"
echo "then successfully drains the queue when connectivity is restored."
echo ""
echo "Prerequisites:"
echo "  1. ESP8266 connected via USB with serial monitor running"
echo "  2. InfluxDB running on Raspberry Pi"
echo ""
echo "Test procedure:"
echo "  1. Note current database URL in serial monitor boot log"
echo "  2. Stop InfluxDB: ssh pi@raspberrypi 'sudo systemctl stop influxdb'"
echo "  3. Wait for 2-3 sensor readings (10-15 minutes at 5min interval)"
echo "  4. Watch serial monitor - should see queue filling:"
echo "     [DB] ✗ POST failed (connection refused)"
echo "     [Queue] ⬆️ Queued reading (1/20)"
echo "     [DB] ✗ POST failed (connection refused)"
echo "     [Queue] ⬆️ Queued reading (2/20)"
echo "  5. Restart InfluxDB: ssh pi@raspberrypi 'sudo systemctl start influxdb'"
echo "  6. Watch serial monitor - should see queue draining:"
echo "     [WiFi] ✓ Connected"
echo "     [Queue] 🔄 Draining 2 queued readings..."
echo "     [DB] ✓ Posted queued reading (HTTP 204)"
echo "     [DB] ✓ Posted queued reading (HTTP 204)"
echo "     [Queue] ✓ All queued readings sent"
echo ""
echo "Expected behavior:"
echo "  - Failed POST attempts increment queue counter"
echo "  - Queue size shown in serial output: (2/20)"
echo "  - After connectivity restored, queue drains automatically"
echo "  - Each queued reading posted individually"
echo "  - Queue clears when all readings sent successfully"
echo ""
echo "Queue limits:"
echo "  - Max capacity: 20 readings"
echo "  - If queue full, oldest reading is dropped"
echo "  - Queue survives ESP8266 soft reset (not power loss)"
echo ""
echo "Commands to run on Raspberry Pi:"
echo ""
echo "Stop InfluxDB:"
echo "  ssh pi@raspberrypi.local 'sudo systemctl stop influxdb'"
echo ""
echo "Start InfluxDB:"
echo "  ssh pi@raspberrypi.local 'sudo systemctl start influxdb'"
echo ""
echo "Check InfluxDB status:"
echo "  ssh pi@raspberrypi.local 'sudo systemctl status influxdb'"
echo ""
echo "Press Enter when ready to begin manual test..."
read

echo ""
echo "Switch to serial monitor terminal to observe queue behavior."
echo "Press Ctrl+C when test is complete."
echo ""

# Keep script running
tail -f /dev/null
